Loginauth
simonaVasilachi/my-personal-project pull request #8
Opened 2021-11-09 11:53 UTC by simonaVasilachi

2021-11-10 14:02 UTC, pionnegru requested changes

2021-11-10 14:02 UTC, pionnegru commented on src/app/Services/users.service.ts
> +  constructor(private http: HttpClient, private usersAPI: UsersAPI) {}
are we using HttpClient?

2021-11-10 14:02 UTC, pionnegru commented on src/app/Services/users.service.ts
> +  private usersUrl = 'http://localhost:3000/users';
are we using this?

2021-11-11 08:22 UTC, simonaVasilachi commented on src/app/Services/auth.guard.ts
> +    const isAuth = this.authService.login('','');
login() has 2 parameters, emailFormControl and passwordFormControl, which are both of type string, so when i call the method i also need to pass 2 arguments

2021-11-16 08:20 UTC, merged